apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Product-App
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/Sada-r/backend/blob/master/mkdocs.yml
  description: This is a Node.js app to get product details
  tags:
    - node

spec:
  type: service
  lifecycle: experimental
  owner: guest
  providesApis:
    - product-api  

    
