apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Product-App
  description: This is a Node.js app to get product details
  annotations:
    backstage.io/managed-by-location: https://github.com/Sada-r/backend/blob/master/catalog-info.yaml
  tags:
    - node js

spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  providesApis:
    - product-api